apiVersion: batch/v1
kind: Job
metadata:
  name: train-job
spec:
  template:
    spec:
      containers:
      - name: train-container
        image: bhavnamatwani/mnist_train
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/model_ckpt"
          name: model-per-volume
      volumes:
      - name: model-per-volume
        persistentVolumeClaim:
          claimName: pvc
      restartPolicy: Never